name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Update draft release notes
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release notes
        uses: release-drafter/release-drafter@v5
        id: something
        with:
          name: Version (insert here)
          tag: Tag placeholder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
